# 端口8001
server:
  port: 8001

# mybatis
mybatis:
  type-aliases-package: cn.techpan.springcloud.entity
  configuration:
    map-underscore-to-camel-case: true                            #驼峰转化
    cache-enabled: true                                           #二级缓存
spring:
  application:
    name: microservicecloud-dept                                  #对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  #数据源
    driver-class-name: org.gjt.mm.mysql.Driver                    #msyqlDriver
    url: jdbc:mysql://localhost:3306/cloudDB01?useSSL=false       #DBName
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                                 #最小维持连接数
      initial-size: 5                                             #初始化连接数
      max-total: 5                                                #最大连接数
      max-wait-millis: 200                                        #等待连接获取的最大超时时间

eureka:
  client:  #将客户端服务注册到Eureka服务列表类
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true                 #访问路径可以显示IP地址

info:
  app.name: cn.techpan.springcloud-microservicecloud
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}